# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1215, 923)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 300, 401, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 330, 700, 500))
        self.label.setAutoFillBackground(True)
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setText("")
        self.label.setObjectName("label")
        self.paramBox = QtWidgets.QGroupBox(self.centralwidget)
        self.paramBox.setGeometry(QtCore.QRect(250, 5, 251, 286))
        self.paramBox.setObjectName("paramBox")
        self.edit_size = QtWidgets.QLineEdit(self.paramBox)
        self.edit_size.setGeometry(QtCore.QRect(130, 240, 111, 20))
        self.edit_size.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_size.setObjectName("edit_size")
        self.label_6 = QtWidgets.QLabel(self.paramBox)
        self.label_6.setGeometry(QtCore.QRect(10, 240, 101, 23))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.edit_epochs = QtWidgets.QLineEdit(self.paramBox)
        self.edit_epochs.setGeometry(QtCore.QRect(130, 220, 111, 20))
        self.edit_epochs.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_epochs.setObjectName("edit_epochs")
        self.edit_ratio = QtWidgets.QLineEdit(self.paramBox)
        self.edit_ratio.setGeometry(QtCore.QRect(130, 200, 111, 20))
        self.edit_ratio.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_ratio.setObjectName("edit_ratio")
        self.label_2 = QtWidgets.QLabel(self.paramBox)
        self.label_2.setGeometry(QtCore.QRect(10, 200, 101, 23))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.paramBox)
        self.label_3.setGeometry(QtCore.QRect(10, 220, 101, 23))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.drop_model = QtWidgets.QComboBox(self.paramBox)
        self.drop_model.setGeometry(QtCore.QRect(130, 20, 111, 22))
        self.drop_model.setObjectName("drop_model")
        self.label_13 = QtWidgets.QLabel(self.paramBox)
        self.label_13.setGeometry(QtCore.QRect(40, 20, 71, 23))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.edit_batch = QtWidgets.QLineEdit(self.paramBox)
        self.edit_batch.setGeometry(QtCore.QRect(130, 260, 111, 20))
        self.edit_batch.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_batch.setObjectName("edit_batch")
        self.label_21 = QtWidgets.QLabel(self.paramBox)
        self.label_21.setGeometry(QtCore.QRect(40, 260, 71, 23))
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.radio_gray = QtWidgets.QCheckBox(self.paramBox)
        self.radio_gray.setGeometry(QtCore.QRect(32, 80, 111, 23))
        self.radio_gray.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radio_gray.setAutoFillBackground(False)
        self.radio_gray.setObjectName("radio_gray")
        self.radio_nestorov = QtWidgets.QCheckBox(self.paramBox)
        self.radio_nestorov.setGeometry(QtCore.QRect(170, 80, 71, 23))
        self.radio_nestorov.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radio_nestorov.setObjectName("radio_nestorov")
        self.radio_plot = QtWidgets.QCheckBox(self.paramBox)
        self.radio_plot.setGeometry(QtCore.QRect(22, 60, 121, 23))
        self.radio_plot.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radio_plot.setObjectName("radio_plot")
        self.edit_lrate = QtWidgets.QLineEdit(self.paramBox)
        self.edit_lrate.setGeometry(QtCore.QRect(130, 120, 111, 20))
        self.edit_lrate.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_lrate.setObjectName("edit_lrate")
        self.label_4 = QtWidgets.QLabel(self.paramBox)
        self.label_4.setGeometry(QtCore.QRect(40, 120, 71, 23))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.paramBox)
        self.label_5.setGeometry(QtCore.QRect(40, 160, 71, 23))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.paramBox)
        self.label_7.setGeometry(QtCore.QRect(40, 140, 71, 23))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.edit_momentum = QtWidgets.QLineEdit(self.paramBox)
        self.edit_momentum.setGeometry(QtCore.QRect(130, 140, 111, 20))
        self.edit_momentum.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_momentum.setObjectName("edit_momentum")
        self.edit_decay = QtWidgets.QLineEdit(self.paramBox)
        self.edit_decay.setGeometry(QtCore.QRect(130, 160, 111, 20))
        self.edit_decay.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_decay.setObjectName("edit_decay")
        self.edit_size.raise_()
        self.label_6.raise_()
        self.edit_epochs.raise_()
        self.edit_ratio.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.drop_model.raise_()
        self.label_13.raise_()
        self.edit_batch.raise_()
        self.label_21.raise_()
        self.radio_gray.raise_()
        self.radio_nestorov.raise_()
        self.radio_plot.raise_()
        self.edit_lrate.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.edit_momentum.raise_()
        self.edit_decay.raise_()
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(420, 300, 41, 23))
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(410, 300, 300, 23))
        self.status.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.status.setFrameShape(QtWidgets.QFrame.Box)
        self.status.setText("")
        self.status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status.setObjectName("status")
        self.resultBox = QtWidgets.QGroupBox(self.centralwidget)
        self.resultBox.setGeometry(QtCore.QRect(510, 5, 201, 286))
        self.resultBox.setObjectName("resultBox")
        self.label_orig = QtWidgets.QLabel(self.resultBox)
        self.label_orig.setGeometry(QtCore.QRect(10, 190, 181, 41))
        self.label_orig.setStyleSheet("")
        self.label_orig.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_orig.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_orig.setObjectName("label_orig")
        self.label_acc = QtWidgets.QLabel(self.resultBox)
        self.label_acc.setGeometry(QtCore.QRect(10, 50, 181, 21))
        self.label_acc.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_acc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_acc.setObjectName("label_acc")
        self.label_acc_2 = QtWidgets.QLabel(self.resultBox)
        self.label_acc_2.setGeometry(QtCore.QRect(10, 80, 181, 101))
        self.label_acc_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_acc_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_acc_2.setObjectName("label_acc_2")
        self.label_pred = QtWidgets.QLabel(self.resultBox)
        self.label_pred.setGeometry(QtCore.QRect(10, 240, 181, 41))
        self.label_pred.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_pred.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_pred.setObjectName("label_pred")
        self.label_time = QtWidgets.QLabel(self.resultBox)
        self.label_time.setGeometry(QtCore.QRect(10, 20, 181, 21))
        self.label_time.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_time.setObjectName("label_time")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 231, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.p_picPath = QtWidgets.QPushButton(self.groupBox_2)
        self.p_picPath.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.p_picPath.setObjectName("p_picPath")
        self.p_train = QtWidgets.QPushButton(self.groupBox_2)
        self.p_train.setEnabled(False)
        self.p_train.setGeometry(QtCore.QRect(120, 20, 101, 31))
        self.p_train.setChecked(False)
        self.p_train.setObjectName("p_train")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 70, 231, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.p_saveM = QtWidgets.QPushButton(self.groupBox_3)
        self.p_saveM.setEnabled(False)
        self.p_saveM.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.p_saveM.setObjectName("p_saveM")
        self.p_loadM = QtWidgets.QPushButton(self.groupBox_3)
        self.p_loadM.setGeometry(QtCore.QRect(120, 20, 101, 31))
        self.p_loadM.setObjectName("p_loadM")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 130, 231, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.p_saveW = QtWidgets.QPushButton(self.groupBox_4)
        self.p_saveW.setEnabled(False)
        self.p_saveW.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.p_saveW.setObjectName("p_saveW")
        self.p_loadW = QtWidgets.QPushButton(self.groupBox_4)
        self.p_loadW.setEnabled(False)
        self.p_loadW.setGeometry(QtCore.QRect(120, 20, 101, 31))
        self.p_loadW.setObjectName("p_loadW")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 190, 231, 101))
        self.groupBox_5.setObjectName("groupBox_5")
        self.p_rand_test = QtWidgets.QPushButton(self.groupBox_5)
        self.p_rand_test.setEnabled(False)
        self.p_rand_test.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.p_rand_test.setObjectName("p_rand_test")
        self.p_select_test = QtWidgets.QPushButton(self.groupBox_5)
        self.p_select_test.setEnabled(False)
        self.p_select_test.setGeometry(QtCore.QRect(120, 20, 101, 31))
        self.p_select_test.setObjectName("p_select_test")
        self.p_tes_folder = QtWidgets.QPushButton(self.groupBox_5)
        self.p_tes_folder.setEnabled(False)
        self.p_tes_folder.setGeometry(QtCore.QRect(10, 60, 101, 31))
        self.p_tes_folder.setObjectName("p_tes_folder")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1215, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PRPD error classification tool"))
        self.paramBox.setTitle(_translate("MainWindow", "Parameter"))
        self.edit_size.setText(_translate("MainWindow", "(128, 128)"))
        self.label_6.setText(_translate("MainWindow", "Bildgröße"))
        self.edit_epochs.setText(_translate("MainWindow", "200"))
        self.edit_ratio.setText(_translate("MainWindow", "0.1"))
        self.label_2.setText(_translate("MainWindow", "Train-Test-Verhältnis"))
        self.label_3.setText(_translate("MainWindow", "Anzahl Epochen"))
        self.label_13.setText(_translate("MainWindow", "Modell"))
        self.edit_batch.setText(_translate("MainWindow", "32"))
        self.label_21.setText(_translate("MainWindow", "Batch-Größe"))
        self.radio_gray.setText(_translate("MainWindow", "Graustufen"))
        self.radio_nestorov.setText(_translate("MainWindow", "Nestorov"))
        self.radio_plot.setText(_translate("MainWindow", "Architektur zeichnen"))
        self.edit_lrate.setText(_translate("MainWindow", "0.01"))
        self.label_4.setText(_translate("MainWindow", "Learning-Rate"))
        self.label_5.setText(_translate("MainWindow", "Decay"))
        self.label_7.setText(_translate("MainWindow", "Momentum"))
        self.edit_momentum.setText(_translate("MainWindow", "0.9"))
        self.edit_decay.setText(_translate("MainWindow", "1e-6"))
        self.label_9.setText(_translate("MainWindow", "Status:"))
        self.resultBox.setTitle(_translate("MainWindow", "Auswertung"))
        self.label_orig.setText(_translate("MainWindow", "Original:"))
        self.label_acc.setText(_translate("MainWindow", "Genauigkeit (1 F):"))
        self.label_acc_2.setText(_translate("MainWindow", "Genauigkeit (2 F):"))
        self.label_pred.setText(_translate("MainWindow", "Vorhersage:"))
        self.label_time.setText(_translate("MainWindow", "Zeit:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Training"))
        self.p_picPath.setText(_translate("MainWindow", "Bildverzeichnis"))
        self.p_train.setText(_translate("MainWindow", "Training"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Modell"))
        self.p_saveM.setText(_translate("MainWindow", "Modell speichern"))
        self.p_loadM.setText(_translate("MainWindow", "Modell laden"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Gewichte"))
        self.p_saveW.setText(_translate("MainWindow", "Gewichte speichern"))
        self.p_loadW.setText(_translate("MainWindow", "Gewichte laden"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Test"))
        self.p_rand_test.setText(_translate("MainWindow", "random Test"))
        self.p_select_test.setText(_translate("MainWindow", "Bild laden + testen"))
        self.p_tes_folder.setText(_translate("MainWindow", "Ordner testen"))

